# Generated by Django 5.2.15 on 2026-06-24 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("KIS", "한국투자증권")], default="KIS", max_length=32
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("LIVE", "실계좌"), ("PAPER", "모의계좌")], max_length=16
                    ),
                ),
                ("account_number", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=100)),
                (
                    "investment_profile",
                    models.CharField(
                        choices=[
                            ("AGGRESSIVE", "공격형"),
                            ("NEUTRAL", "중립형"),
                            ("CONSERVATIVE", "안정형"),
                        ],
                        default="NEUTRAL",
                        max_length=32,
                    ),
                ),
                ("app_key_encrypted", models.TextField()),
                ("app_secret_encrypted", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌 목록",
                "db_table": "acc_account",
            },
        ),
        migrations.CreateModel(
            name="BrokerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token_encrypted", models.TextField()),
                ("token_type", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("issued_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker 토큰",
                "verbose_name_plural": "Broker 토큰 목록",
                "db_table": "acc_broker_token",
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_active"], name="acc_account_user_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["broker", "account_type"], name="acc_account_broker_type_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "broker", "account_type", "account_number")},
        ),
        migrations.AddIndex(
            model_name="brokertoken",
            index=models.Index(
                fields=["account", "expires_at"], name="acc_broker_token_acct_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertoken",
            index=models.Index(
                fields=["revoked_at"], name="acc_broker_token_revoked_idx"
            ),
        ),
    ]
