# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('SCHEDULED', '스케줄됨'), ('MANUAL', '수동')], max_length=32)),
                ('status', models.CharField(choices=[('RUNNING', '실행중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField(help_text='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, help_text='종료 시각', null=True)),
                ('error_message', models.TextField(blank=True, help_text='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '계좌 실행 결과',
                'verbose_name_plural': '계좌 실행 결과 목록',
                'db_table': 'acc_execution_run',
            },
        ),
        migrations.CreateModel(
            name='PositionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=8, help_text='수량 증감', max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, help_text='기준 가격', max_digits=18)),
                ('reason', models.TextField(blank=True, help_text='사유')),
                ('occurred_at', models.DateTimeField(help_text='발생 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '포지션 원장',
                'verbose_name_plural': '포지션 원장 목록',
                'db_table': 'acc_position_ledger',
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, help_text='현금 잔고', max_digits=18)),
                ('total_asset_value', models.DecimalField(decimal_places=2, help_text='총 평가 금액', max_digits=18)),
                ('snapshot_payload', models.JSONField(blank=True, default=dict, help_text='상세 스냅샷')),
                ('snapshotted_at', models.DateTimeField(help_text='스냅샷 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='account.account')),
            ],
            options={
                'verbose_name': '잔고 스냅샷',
                'verbose_name_plural': '잔고 스냅샷 목록',
                'db_table': 'acc_balance_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAWAL', '출금'), ('BUY', '매수'), ('SELL', '매도'), ('FEE', '수수료'), ('TAX', '세금'), ('ADJUSTMENT', '조정')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='증감 금액', max_digits=18)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('reason', models.TextField(blank=True, help_text='사유')),
                ('occurred_at', models.DateTimeField(help_text='발생 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledgers', to='account.account')),
            ],
            options={
                'verbose_name': '현금 원장',
                'verbose_name_plural': '현금 원장 목록',
                'db_table': 'acc_cash_ledger',
            },
        ),
    ]
