# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_executionrun_positionledger_balancesnapshot_and_more'),
        ('order', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashledger',
            name='trade_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_ledgers', to='order.tradeexecution'),
        ),
        migrations.AddField(
            model_name='executionrun',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='account.account'),
        ),
        migrations.AddField(
            model_name='positionledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_ledgers', to='account.account'),
        ),
        migrations.AddField(
            model_name='positionledger',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_ledgers', to='stock.stock'),
        ),
        migrations.AddField(
            model_name='positionledger',
            name='trade_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_ledgers', to='order.tradeexecution'),
        ),
        migrations.AddIndex(
            model_name='balancesnapshot',
            index=models.Index(fields=['account', '-snapshotted_at'], name='acc_bal_snap_acc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='cashledger',
            index=models.Index(fields=['account', '-occurred_at'], name='acc_cash_acc_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='cashledger',
            index=models.Index(fields=['trade_execution'], name='acc_cash_trade_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['account', '-started_at'], name='acc_exec_run_acc_start_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['status', '-started_at'], name='acc_exec_run_sts_start_idx'),
        ),
        migrations.AddIndex(
            model_name='positionledger',
            index=models.Index(fields=['account', 'stock', '-occurred_at'], name='acc_pos_acc_stk_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='positionledger',
            index=models.Index(fields=['trade_execution'], name='acc_pos_trade_exec_idx'),
        ),
    ]
