# Generated by Django 5.2.15 on 2026-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=32)),
                ("artifact_uri", models.TextField(help_text="모델 파일 스토리지 경로")),
                (
                    "artifact_checksum",
                    models.CharField(help_text="파일 검증용 체크섬", max_length=128),
                ),
                (
                    "training_dataset_id",
                    models.BigIntegerField(
                        blank=True, help_text="학습 데이터셋 ID", null=True
                    ),
                ),
                (
                    "metrics_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="학습 및 검증 평가지표"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "학습중"),
                            ("READY", "준비완료"),
                            ("DEPLOYED", "배포됨"),
                            ("RETIRED", "종료됨"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(blank=True, help_text="학습 완료 시각", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retired_at",
                    models.DateTimeField(blank=True, help_text="사용 중지 시각", null=True),
                ),
            ],
            options={
                "verbose_name": "모델 산출물",
                "verbose_name_plural": "모델 산출물 목록",
                "db_table": "sys_model_artifact",
                "indexes": [
                    models.Index(
                        fields=["model_name", "status"],
                        name="sys_model_art_name_stat_idx",
                    )
                ],
                "unique_together": {("model_name", "version")},
            },
        ),
    ]
