# Generated by Django 5.2.15 on 2026-07-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
        ("order", "0002_initial"),
        ("system", "0001_initial"),
        (
            "trading",
            "0003_decisionlog_decision_payload_decisionlog_final_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=32)),
                ("source_started_at", models.DateTimeField(help_text="학습 데이터 시작 시각")),
                ("source_ended_at", models.DateTimeField(help_text="학습 데이터 종료 시각")),
                (
                    "feature_definition",
                    models.JSONField(blank=True, default=dict, help_text="Feature 정의"),
                ),
                (
                    "label_definition",
                    models.JSONField(
                        blank=True, default=dict, help_text="Label 정의(배리어/비용 등)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BUILDING", "생성중"),
                            ("READY", "준비완료"),
                            ("RETIRED", "종료됨"),
                        ],
                        default="BUILDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="생성 완료 시각", null=True),
                ),
            ],
            options={
                "verbose_name": "학습 데이터셋",
                "verbose_name_plural": "학습 데이터셋 목록",
                "db_table": "sys_training_dataset",
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="sys_train_ds_status_idx"
                    )
                ],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="TrainingDatasetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.SmallIntegerField(help_text="1 = 수익, 0 = 손실")),
                (
                    "realized_return",
                    models.DecimalField(
                        decimal_places=6, help_text="비용 차감 실현 수익률", max_digits=10
                    ),
                ),
                (
                    "feature_payload",
                    models.JSONField(blank=True, default=dict, help_text="학습용 Feature"),
                ),
                (
                    "label_payload",
                    models.JSONField(blank=True, default=dict, help_text="Label 생성 근거"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_items",
                        to="market.featuresnapshot",
                    ),
                ),
                (
                    "trade_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_items",
                        to="order.tradeexecution",
                    ),
                ),
                (
                    "trader_decision_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="실현 거래 기반 샘플일 때의 최종 판단 로그",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_items",
                        to="trading.decisionlog",
                    ),
                ),
                (
                    "training_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="system.trainingdataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "학습 샘플",
                "verbose_name_plural": "학습 샘플 목록",
                "db_table": "sys_training_dataset_item",
                "indexes": [
                    models.Index(
                        fields=["training_dataset"], name="sys_train_item_ds_idx"
                    ),
                    models.Index(fields=["label"], name="sys_train_item_label_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("label__in", (0, 1))),
                        name="sys_train_item_label_binary",
                    )
                ],
            },
        ),
    ]
