# Generated by Django 5.2.15 on 2026-07-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_trainingdataset_trainingdatasetitem"),
        (
            "trading",
            "0003_decisionlog_decision_payload_decisionlog_final_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "활성"), ("RETIRED", "종료")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("deployed_at", models.DateTimeField(help_text="배포 시각")),
                (
                    "retired_at",
                    models.DateTimeField(blank=True, help_text="종료 시각", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="system.modelartifact",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_deployments",
                        to="trading.trader",
                    ),
                ),
            ],
            options={
                "verbose_name": "모델 배포",
                "verbose_name_plural": "모델 배포 목록",
                "db_table": "sys_model_deployment",
                "indexes": [
                    models.Index(
                        fields=["trader", "status"], name="sys_model_dep_trader_idx"
                    ),
                    models.Index(
                        fields=["model_artifact", "status"],
                        name="sys_model_dep_art_idx",
                    ),
                ],
            },
        ),
    ]
