# Generated by Django 5.2.15 on 2026-06-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("KRX", "KRX"),
                            ("KOSPI", "KOSPI"),
                            ("KOSDAQ", "KOSDAQ"),
                        ],
                        max_length=32,
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "원화")], default="KRW", max_length=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "종목",
                "verbose_name_plural": "종목 목록",
                "db_table": "stk_stock",
                "indexes": [
                    models.Index(fields=["symbol"], name="stk_stock_symbol_idx"),
                    models.Index(
                        fields=["market", "is_active"],
                        name="stk_stock_market_active_idx",
                    ),
                ],
                "unique_together": {("market", "symbol")},
            },
        ),
    ]
