# Generated by Django 5.2.15 on 2026-07-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniverseMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "universe",
                    models.CharField(
                        choices=[
                            ("KOSPI200", "코스피200"),
                            ("KOSDAQ150", "코스닥150"),
                            ("CUSTOM", "사용자정의"),
                        ],
                        max_length=32,
                    ),
                ),
                ("effective_from", models.DateTimeField(help_text="편입 시각 (구간 시작, 포함)")),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="편출 시각 (구간 끝, 미포함). None이면 현재 편입 중",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universe_memberships",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "유니버스 편입 이력",
                "verbose_name_plural": "유니버스 편입 이력 목록",
                "db_table": "stk_universe_membership",
                "indexes": [
                    models.Index(
                        fields=["universe", "stock", "-effective_from"],
                        name="stk_univ_mem_uni_stk_idx",
                    ),
                    models.Index(
                        fields=["universe", "effective_from", "effective_to"],
                        name="stk_univ_mem_uni_range_idx",
                    ),
                ],
            },
        ),
    ]
