# Generated by Django 5.2.15 on 2026-06-24 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(help_text="개발자 또는 전략 네임스페이스", max_length=64),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(help_text="Strategy 고유 코드", max_length=64)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Strategy 소유 개발자",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategy 목록",
                "db_table": "trd_strategy",
            },
        ),
        migrations.CreateModel(
            name="StrategyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="사람이 읽는 버전 (예: v1.0.0)", max_length=32),
                ),
                (
                    "module_path",
                    models.CharField(help_text="Python module path", max_length=255),
                ),
                (
                    "class_name",
                    models.CharField(help_text="Strategy class name", max_length=100),
                ),
                (
                    "commit_hash",
                    models.CharField(blank=True, help_text="코드 커밋 식별자", max_length=64),
                ),
                (
                    "config_schema",
                    models.JSONField(blank=True, default=dict, help_text="설정 스키마"),
                ),
                (
                    "default_config",
                    models.JSONField(blank=True, default=dict, help_text="기본 설정"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "초안"), ("ACTIVE", "활성"), ("RETIRED", "종료")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy 버전",
                "verbose_name_plural": "Strategy 버전 목록",
                "db_table": "trd_strategy_version",
            },
        ),
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(help_text="계좌 내 고유 코드", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "활성"),
                            ("PAUSED", "일시정지"),
                            ("STOPPED", "중지"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "position_size_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.1,
                        help_text="기본 포지션 비율 (0.0 ~ 1.0)",
                        max_digits=10,
                    ),
                ),
                (
                    "entry_threshold",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.5,
                        help_text="기본 진입 기준 Score",
                        max_digits=10,
                    ),
                ),
                (
                    "stop_loss_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.03,
                        help_text="손절 기준 비율",
                        max_digits=10,
                    ),
                ),
                (
                    "take_profit_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.05,
                        help_text="익절 기준 비율",
                        max_digits=10,
                    ),
                ),
                (
                    "max_exposure_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.3,
                        help_text="최대 노출 비율",
                        max_digits=10,
                    ),
                ),
                (
                    "ml_filter_enabled",
                    models.BooleanField(default=False, help_text="ML Filter 사용 여부"),
                ),
                (
                    "config_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Trader별 추가 설정"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traders",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trader",
                "verbose_name_plural": "Trader 목록",
                "db_table": "trd_trader",
            },
        ),
        migrations.CreateModel(
            name="TraderStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.SmallIntegerField(
                        choices=[(1, "Slot 1"), (2, "Slot 2")], help_text="Slot 1 또는 2"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Score 조합 가중치",
                        max_digits=10,
                    ),
                ),
                (
                    "config_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Trader에 연결된 Strategy 설정"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trader_strategies",
                        to="trading.strategyversion",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trader_strategies",
                        to="trading.trader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trader-Strategy 연결",
                "verbose_name_plural": "Trader-Strategy 연결 목록",
                "db_table": "trd_trader_strategy",
            },
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(
                fields=["owner", "is_active"], name="trd_strategy_owner_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(
                fields=["namespace", "is_active"], name="trd_strategy_ns_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="strategy",
            unique_together={("namespace", "code")},
        ),
        migrations.AddIndex(
            model_name="strategyversion",
            index=models.Index(
                fields=["strategy", "status"], name="trd_sv_strategy_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="strategyversion",
            unique_together={("strategy", "version")},
        ),
        migrations.AddIndex(
            model_name="trader",
            index=models.Index(
                fields=["account", "status"], name="trd_trader_account_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trader",
            unique_together={("account", "code")},
        ),
        migrations.AddIndex(
            model_name="traderstrategy",
            index=models.Index(
                fields=["strategy_version", "is_active"], name="trd_ts_sv_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="traderstrategy",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0)), name="trd_ts_weight_positive"
            ),
        ),
    ]
