# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(help_text='BUY / SELL / HOLD', max_length=16)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trader_decisions', to='stock.stock')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='trading.trader')),
            ],
            options={
                'verbose_name': '매매 판단 로그',
                'verbose_name_plural': '매매 판단 로그 목록',
                'db_table': 'trd_decision_log',
            },
        ),
        migrations.CreateModel(
            name='TraderTargetStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_threshold', models.DecimalField(decimal_places=2, default=0.5, help_text='ML 필터 임계값 (예: 0.50=B타입, 0.70=A타입)', max_digits=4)),
                ('is_active', models.BooleanField(default=True, help_text='현재 매매 대상 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_by', to='stock.stock')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_stocks', to='trading.trader')),
            ],
            options={
                'verbose_name': 'Trader 대상 종목',
                'verbose_name_plural': 'Trader 대상 종목 목록',
                'db_table': 'trd_trader_target_stock',
                'indexes': [models.Index(fields=['trader', 'is_active'], name='trd_target_trader_active_idx')],
                'unique_together': {('trader', 'stock')},
            },
        ),
    ]
