# Generated by Django 5.2.15 on 2026-07-01 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_cashledger_trade_execution_executionrun_account_and_more"),
        ("market", "0001_initial"),
        ("stock", "0001_initial"),
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "실행중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(help_text="시작 시각")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, help_text="종료 시각", null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="실패 사유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trader_runs",
                        to="account.executionrun",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_runs",
                        to="trading.trader",
                    ),
                ),
            ],
            options={
                "verbose_name": "트레이더 실행 결과",
                "verbose_name_plural": "트레이더 실행 결과 목록",
                "db_table": "trd_execution_run",
            },
        ),
        migrations.CreateModel(
            name="StrategyDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "매수"), ("SELL", "매도"), ("HOLD", "관망")],
                        max_length=8,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=6, help_text="매수/매도 강도 (0~1)", max_digits=10
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="판단 근거")),
                ("decided_at", models.DateTimeField(help_text="판단 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.featuresnapshot",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_decisions",
                        to="stock.stock",
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="trading.strategyversion",
                    ),
                ),
                (
                    "trader_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_decisions",
                        to="trading.traderexecutionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "전략 판단 로그",
                "verbose_name_plural": "전략 판단 로그 목록",
                "db_table": "trd_strategy_decision_log",
            },
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_action",
                    models.CharField(
                        choices=[("BUY", "매수"), ("SELL", "매도"), ("HOLD", "관망")],
                        max_length=8,
                    ),
                ),
                (
                    "target_quantity",
                    models.DecimalField(
                        decimal_places=8, default=0, help_text="목표 주문 수량", max_digits=18
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="최종 판단 근거")),
                ("decided_at", models.DateTimeField(help_text="판단 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_decisions",
                        to="stock.stock",
                    ),
                ),
                (
                    "trader_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_decisions",
                        to="trading.traderexecutionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "트레이더 최종 판단 로그",
                "verbose_name_plural": "트레이더 최종 판단 로그 목록",
                "db_table": "trd_decision_log",
            },
        ),
        migrations.AddIndex(
            model_name="traderexecutionrun",
            index=models.Index(
                fields=["trader", "-started_at"], name="trd_exec_run_trd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="traderexecutionrun",
            index=models.Index(fields=["account_run"], name="trd_exec_run_acc_run_idx"),
        ),
        migrations.AddIndex(
            model_name="strategydecisionlog",
            index=models.Index(
                fields=["strategy_version", "stock", "-decided_at"],
                name="trd_str_dec_ver_stk_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strategydecisionlog",
            index=models.Index(fields=["trader_run"], name="trd_str_dec_run_idx"),
        ),
        migrations.AddIndex(
            model_name="decisionlog",
            index=models.Index(
                fields=["trader_run", "stock", "-decided_at"],
                name="trd_dec_log_run_stk_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionlog",
            index=models.Index(
                fields=["final_action", "-decided_at"], name="trd_dec_log_act_idx"
            ),
        ),
    ]
