# Generated by Django 5.2.15 on 2026-07-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
        ("trading", "0002_traderexecutionrun_strategydecisionlog_decisionlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionlog",
            name="decision_payload",
            field=models.JSONField(
                blank=True, default=dict, help_text="최종 판단 Snapshot"
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="final_score",
            field=models.DecimalField(
                decimal_places=6, default=0.0, help_text="최종 Score", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="max_exposure_ratio",
            field=models.DecimalField(
                decimal_places=6, default=0.0, help_text="적용 최대 노출 비율", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="position_size_ratio",
            field=models.DecimalField(
                decimal_places=6, default=0.0, help_text="적용 포지션 비율", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="stop_loss_ratio",
            field=models.DecimalField(
                decimal_places=6, default=0.0, help_text="적용 손절 기준", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="take_profit_ratio",
            field=models.DecimalField(
                decimal_places=6, default=0.0, help_text="적용 익절 기준", max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="MLOutputLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_probability",
                    models.DecimalField(
                        decimal_places=6, help_text="거래 성공 가능성", max_digits=10
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=6, help_text="리스크 점수", max_digits=10
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(
                        decimal_places=6, help_text="기대 수익", max_digits=10
                    ),
                ),
                (
                    "input_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="ML 입력 Snapshot"
                    ),
                ),
                (
                    "output_payload",
                    models.JSONField(blank=True, default=dict, help_text="ML 출력 원본"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_outputs",
                        to="system.modelartifact",
                    ),
                ),
                (
                    "trader_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_outputs",
                        to="trading.traderexecutionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML 판단 로그",
                "verbose_name_plural": "ML 판단 로그 목록",
                "db_table": "trd_ml_output_log",
            },
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="ml_output_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions",
                to="trading.mloutputlog",
            ),
        ),
        migrations.AddIndex(
            model_name="mloutputlog",
            index=models.Index(fields=["trader_run"], name="trd_ml_out_run_idx"),
        ),
        migrations.AddIndex(
            model_name="mloutputlog",
            index=models.Index(
                fields=["model_artifact", "-created_at"], name="trd_ml_out_art_idx"
            ),
        ),
    ]
