# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1분'), ('5m', '5분'), ('15m', '15분'), ('1d', '1일')], max_length=16)),
                ('opened_at', models.DateTimeField(help_text='캔들 시작 시각')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(help_text='데이터 출처', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='원본 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stock.stock')),
            ],
            options={
                'verbose_name': '시세 캔들',
                'verbose_name_plural': '시세 캔들 목록',
                'db_table': 'mkt_candle',
                'indexes': [models.Index(fields=['stock', 'timeframe', '-opened_at'], name='mkt_candle_stk_tf_open_idx')],
                'unique_together': {('stock', 'timeframe', 'opened_at', 'source')},
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(help_text='Feature 기준 timeframe', max_length=16)),
                ('feature_payload', models.JSONField(default=dict, help_text='Feature Vector')),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='원천 데이터 참조 요약')),
                ('captured_at', models.DateTimeField(help_text='Feature 기준 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='stock.stock')),
            ],
            options={
                'verbose_name': 'Feature 스냅샷',
                'verbose_name_plural': 'Feature 스냅샷 목록',
                'db_table': 'mkt_feature_snapshot',
                'indexes': [models.Index(fields=['stock', 'timeframe', '-captured_at'], name='mkt_feat_stk_tf_cap_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('BULL', '상승장'), ('SIDEWAYS', '횡보장'), ('BEAR', '하락장')], max_length=16)),
                ('confidence_score', models.DecimalField(decimal_places=6, help_text='판단 신뢰도', max_digits=10)),
                ('parameter_payload', models.JSONField(blank=True, default=dict, help_text='Trader/Strategy 전달용 시장 파라미터')),
                ('reason', models.TextField(blank=True, help_text='판단 근거')),
                ('analyzed_at', models.DateTimeField(help_text='분석 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regime_snapshots', to='stock.stock')),
            ],
            options={
                'verbose_name': '시장 국면 스냅샷',
                'verbose_name_plural': '시장 국면 스냅샷 목록',
                'db_table': 'mkt_regime_snapshot',
                'indexes': [models.Index(fields=['stock', '-analyzed_at'], name='mkt_regime_stk_analyzed_idx'), models.Index(fields=['regime', '-analyzed_at'], name='mkt_regime_reg_analyzed_idx')],
            },
        ),
    ]
