# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_executionrun_positionledger_balancesnapshot_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PENDING', '대기중'), ('ACCEPTED', '접수완료'), ('PARTIALLY_FILLED', '부분체결'), ('FILLED', '전체체결'), ('CANCELED', '취소됨'), ('REJECTED', '거절됨')], max_length=32)),
                ('broker_status', models.CharField(blank=True, help_text='Broker 원본 상태', max_length=64)),
                ('event_payload', models.JSONField(blank=True, default=dict, help_text='원본 이벤트')),
                ('occurred_at', models.DateTimeField(help_text='이벤트 발생 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '주문 이벤트',
                'verbose_name_plural': '주문 이벤트 목록',
                'db_table': 'ord_order_event',
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=8)),
                ('executed_quantity', models.DecimalField(decimal_places=8, help_text='체결 수량', max_digits=18)),
                ('executed_price', models.DecimalField(decimal_places=2, help_text='체결 가격', max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='수수료', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='세금', max_digits=18)),
                ('slippage_amount', models.DecimalField(decimal_places=2, default=0, help_text='슬리피지', max_digits=18)),
                ('broker_execution_id', models.CharField(blank=True, help_text='Broker 체결번호', max_length=100, null=True)),
                ('executed_at', models.DateTimeField(help_text='체결 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '체결',
                'verbose_name_plural': '체결 목록',
                'db_table': 'ord_trade_execution',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=8)),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='주문 수량', max_digits=18)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, help_text='지정가', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ACCEPTED', '접수완료'), ('PARTIALLY_FILLED', '부분체결'), ('FILLED', '전체체결'), ('CANCELED', '취소됨'), ('REJECTED', '거절됨')], default='PENDING', max_length=32)),
                ('broker_order_id', models.CharField(blank=True, help_text='Broker 주문번호', max_length=100, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='주문 요청 원본')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='주문 응답 원본')),
                ('requested_at', models.DateTimeField(help_text='요청 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='account.account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stock.stock')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'ord_order',
            },
        ),
    ]
