# Generated by Django 5.2.15 on 2026-07-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_cashledger_trade_execution_executionrun_account_and_more'),
        ('order', '0001_initial'),
        ('stock', '0001_initial'),
        ('trading', '0002_decisionlog_tradertargetstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trader_decision_log',
            field=models.ForeignKey(help_text='주문 생성의 원인이 된 최종 판단', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.decisionlog'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.order'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='account.account'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='order.order'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='stock.stock'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', '-requested_at'], name='ord_order_acc_req_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stock', '-requested_at'], name='ord_order_stk_req_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='ord_order_broker_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-requested_at'], name='ord_order_sts_req_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'occurred_at'], name='ord_event_ord_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='ord_event_type_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['account', '-executed_at'], name='ord_exec_acc_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['stock', '-executed_at'], name='ord_exec_stk_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['order'], name='ord_exec_order_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['broker_execution_id'], name='ord_exec_broker_id_idx'),
        ),
    ]
